server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_redis?serverTimezone=UTC
    username: root
    password: root
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      enabled: false
      max-connections: 10

queueName: myJob
topicName: topic_myJob


#mybatis:
 # mapper-locations: classpath:/mapper/*.xml
  #type-aliases-package: com.mq.demo.entities
